### ISSUE TITLE
Doesn't pass the latest tests

### ISSUE THREAD

**Issue by Kagami** [rfk/wasm-polyfill#5]
I've updated spec submodule to commit https://github.com/WebAssembly/spec/commit/105c5ea207ed3bc7194a931e6abcf9e6b3ae5d58 and tests fail with:

```
$ make test-bail
./node_modules/.bin/mocha --timeout 10000 --bail ./tests/


  The WebAssembly polyfill
    ✓ should pass the "address.wast" test suite (104ms)
(node:12565) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
    ✓ should pass the "align.wast" test suite (88ms)
(node:12565) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
    ✓ should pass the "binary.wast" test suite (97ms)
(node:12565) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
/tmp/block.wast.js:91
  throw new Error("Wasm validation failure expected");
  ^

Error: Wasm validation failure expected
    at assert_invalid (/tmp/block.wast.js:91:9)
    at Object.<anonymous> (/tmp/block.wast.js:223:1)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:190:16)
    at bootstrap_node.js:662:3
    1) should pass the "block.wast" test suite


  3 passing (409ms)
  1 failing

  1) The WebAssembly polyfill should pass the "block.wast" test suite:
     Error: done() invoked with non-Error: 1
      at ChildProcess.<anonymous> (tests/spec.js:78:38)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)



make: *** [Makefile:32: test-bail] Error 1
```

(I've also set `VERSION_NUMBER` to `0x1` in `src/constants.js`)

**Comment by rfk** [comment]
Thanks for reaching out.  Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
